import {Api} from '@infoportal/api-sdk'

export const questionTypeMuiIcon: Record<Api.Form.QuestionType, string> = {
  begin_group: 'folder_open',
  end_group: 'folder',
  begin_repeat: 'repeat',
  end_repeat: 'repeat',
  select_one: 'radio_button_checked',
  select_multiple: 'check_box',
  select_one_from_file: 'attach_file',
  today: 'today',
  date: 'calendar_month',
  datetime: 'event',
  text: 'format_align_left',
  integer: 'pin',
  decimal: '123',
  file: 'attach_file',
  image: 'image',
  note: 'sticky_note_2',
  calculate: 'functions',
  username: 'short_text',
  end: 'calendar_month',
  start: 'calendar_month',
  geopoint: 'location_on',
  deviceid: '',
  geoshape: 'map',
  audio: 'mic',
  barcode: 'barcode',
  geotrace: 'route',
  range: 'arrow_range',
  video: 'videocam',
}
